services:
  cloudbeaver:
      image: dbeaver/cloudbeaver:latest
      container_name: cloudbeaver
      restart: unless-stopped
      ports:
       - '8978:8978'
      volumes: 
       - cloudbeaver:/opt/cloudbeaver/workspace          
      networks:
      - sparkanos  

volumes:
  cloudbeaver:
    driver: local

networks:
  sparkanos:
    external: true

